// -------------------------------
// Generated by TypeForwardedTo.tt
// -------------------------------
using System.Runtime.CompilerServices;
#pragma warning disable 612

#if RETRO
[assembly: TypeForwardedTo(typeof(MetroTrilithon.RetroTrilithon))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Interactivity.ScrollBarThresholdBehavior))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Interactivity.TaskbarMessage))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Interactivity.TaskbarMessageAction))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Converters.EnumToBooleanConverter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Converters.NullToVisibilityConverter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Converters.ReverseBooleanConverter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Converters.StringToVisiblityConverter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Converters.UniversalBooleanToVisibilityConverter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.CallMethodButton))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.Extensions))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.HyperlinkEx))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.RichTextInlinePresenter))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.RichText))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.Link))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.Regular))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.RichTextView))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.SortButton))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.SortDirection))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.TabHeader))]	
[assembly: TypeForwardedTo(typeof(MetroTrilithon.Controls.WebBrowserHelper))]	
#endif
