using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Amethystra.ThemeResourceKeyGen;

internal static class Program
{
    private const string _themeResourceTypeName = "Wpf.Ui.Markup.ThemeResource";
    private const string _unknownThemeResourceName = "Unknown";
    private const string _newLine = "\r\n";

    public static int Main(string[] args)
    {
        try
        {
            var options = Options.Parse(args);
            var themeResources = GetThemeResources(options.AssemblyPath);
            var source = RenderSource(options.Namespace, themeResources);

            WriteFile(options.OutputPath, source);

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 1;
        }
    }

    private static string[] GetThemeResources(string assemblyPath)
    {
        var assembly = Assembly.LoadFrom(assemblyPath);
        var themeResourceType = assembly.GetType(_themeResourceTypeName, throwOnError: true)
            ?? throw new InvalidOperationException($"{_themeResourceTypeName} was not found.");

        return themeResourceType.IsEnum
            ? [.. Enum.GetNames(themeResourceType).Where(x => x != _unknownThemeResourceName)]
            : throw new InvalidOperationException($"{_themeResourceTypeName} is not an enum.");
    }

    private static string RenderSource(string @namespace, string[] themeResources)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated />").Append(_newLine);
        sb.Append(_newLine);
        sb.Append("namespace ").Append(@namespace).Append(';').Append(_newLine);
        sb.Append(_newLine);
        sb.Append("public static partial class ThemeResourceKeys").Append(_newLine);
        sb.Append('{').Append(_newLine);

        foreach (var name in themeResources)
        {
            sb.Append("    public const string ")
                .Append(name)
                .Append(" = \"")
                .Append(name)
                .Append("\";")
                .Append(_newLine);
        }

        sb.Append('}').Append(_newLine);

        return sb.ToString();
    }

    private static void WriteFile(string outputPath, string source)
    {
        var directoryPath = Path.GetDirectoryName(outputPath)
            ?? throw new InvalidOperationException("Output path directory was not resolved.");

        Directory.CreateDirectory(directoryPath);

        if (File.Exists(outputPath))
        {
            var current = File.ReadAllText(outputPath, Encoding.UTF8);
            if (StringComparer.Ordinal.Equals(current, source))
            {
                return;
            }
        }

        File.WriteAllText(outputPath, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    private sealed class Options(string assemblyPath, string outputPath, string @namespace)
    {
        public string AssemblyPath { get; } = assemblyPath;

        public string OutputPath { get; } = outputPath;

        public string Namespace { get; } = @namespace;

        public static Options Parse(string[] args)
        {
            string? assemblyPath = null;
            string? outputPath = null;
            string? @namespace = null;

            for (var i = 0; i < args.Length; i++)
            {
                switch (args[i])
                {
                    case "--assembly-path":
                        assemblyPath = GetValue(args, ref i);
                        break;
                    case "--output-path":
                        outputPath = GetValue(args, ref i);
                        break;
                    case "--namespace":
                        @namespace = GetValue(args, ref i);
                        break;
                    default:
                        throw new ArgumentException($"Unknown argument: {args[i]}");
                }
            }

            if (string.IsNullOrWhiteSpace(assemblyPath))
            {
                throw new ArgumentException("--assembly-path is required.");
            }

            if (File.Exists(assemblyPath) == false)
            {
                throw new FileNotFoundException("Assembly path was not found.", assemblyPath);
            }

            if (string.IsNullOrWhiteSpace(outputPath))
            {
                throw new ArgumentException("--output-path is required.");
            }

            if (string.IsNullOrWhiteSpace(@namespace))
            {
                throw new ArgumentException("--namespace is required.");
            }

            return new Options(Path.GetFullPath(assemblyPath), Path.GetFullPath(outputPath), @namespace);
        }

        private static string GetValue(string[] args, ref int index)
            => ++index < args.Length
                ? args[index]
                : throw new ArgumentException("Argument value is missing.");
    }
}
